sudo: true

dist: xenial
arch:
  - amd64
  - ppc64le
language: c++

sudo: true

dist: xenial
arch:
  - amd64
  - ppc64le
language: c++
addons:
  apt:
     packages:
       - build-essential
       - cmake
       - gcc
       - libudev-dev
       - libnl-3-dev
       - libnl-route-3-dev
       - ninja-build
       - pkg-config
       - valgrind
       - python3-dev
       - cython3
       - python3-docutils
       - pandoc

script:
  - bash build.sh
  - cd tests
  - ./run_tests.py
